import 'dart:async';
import 'dart:convert';
import 'dart:developer';
import 'dart:io';
import 'dart:math';
import 'dart:ui' as ui;
import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'package:image_picker/image_picker.dart';
import 'package:quill_html_editor/quill_html_editor.dart';
import 'package:image_stack/image_stack.dart';
import 'package:intl/intl.dart';
// import 'package:location/location.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:permission_handler/permission_handler.dart' as permission;
import 'package:supercharged/supercharged.dart';
import 'package:syncfusion_flutter_calendar/calendar.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:xpecta/shared/shared.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:http/http.dart' as http;

part 'profile/sign_in.dart';
part 'profile/sign_up.dart';
part 'profile/forgot_password.dart';
part 'profile/edit_akun.dart';
part 'profile/kontak.dart';
part 'profile/edit_password.dart';
part 'option/tnc.dart';
part 'main/home.dart';
part 'main/janji_berlangsung.dart';
part 'main/janji_selesai.dart';
part 'main/janji_batal.dart';
part 'main/pesan.dart';
part 'main/profil.dart';
part 'detail/detail_dokter.dart';
part 'detail/detail_covid_tips.dart';
part 'detail/detail_covid_test.dart';
part 'detail/detail_covid_paket.dart';
part 'detail/detail_covid_vaksinasi.dart';
part 'detail/detail_fasilitas.dart';
part 'detail/detail_rs.dart';
part 'detail/detail_obat.dart';
part 'detail/detail_ambulans.dart';
part 'detail/detail_farmasi.dart';
part 'detail/detail_dokter_list.dart';
part 'detail/detail_pemeriksaan.dart';
part 'detail/detail_pencarian_penyakit.dart';
part 'detail/detail_pencarian_obat.dart';
part 'detail/detail_hasil_penyakit.dart';
part 'detail/detail_hasil_obat.dart';
part 'detail/detail_penyakit.dart';
part 'detail/detail_buat_janji.dart';
part 'detail/detail_pesan.dart';
